README.md

Contributor graph updated

---

package-lock.json
src/components/HomeOurValues/OurValues1.tsx
src/components/HomeOurValues/Values.css

I have also added transition effect on hover so it will scale up as shown in growth section and then slowly turn back to it's original size.

made changes in the our values section

---

src/components/Blogs/Blogs.tsx
src/components/HeroSection/styles.css
src/components/HomeHeader/HomeHeader.tsx
src/components/HomeHeader/styles.ts
src/components/HomeOurValues/Values.css
src/components/ImageGallery/ImageGallery.tsx
src/components/ImageGallery/imagegallery.css
src/components/MainBlogs/MainBlogs.tsx
src/components/MainBlogs/blog.css
src/components/MainHeader/styles.ts
src/components/MapBox/MapBox.tsx
src/components/MapBox/map.css
src/components/Navbar/Navbar.tsx
src/components/Navbar/styles.ts

I have add responsiveness to the page.
So,please check and inform me if you wanna any other changes.
issues #92

Responsiveness added to page

---

.github/ISSUES_TEMPLATE/Bug_report.yml

Added the issue template for bug report.
closes issue number #101

Create issue template for bug report

---

src/components/MapBox/MapBox.tsx

Corrected typo in MapBox

---

Contributing.md

Closes #83 
Added Contributing.md file in the repository.
@Gaurav-Verma07 Thank you for this opportunity.

Contributing.md file added

---

Code_of_Conduct.md

Closes #84 
A code of conduct file is added.
@Gaurav-Verma07 Thank you for this opportunity.

Code of conduct file added

---

src/components/HeroSection/HeroSection.tsx

Closes #106 
I have rectified the typographical error in the hero section, replacing "orphange" with "orphanage."

Corrected typo in Hero Section

---

.github/ISSUES_TEMPLATE/feature.yml

Closes issue number #100
Added feature issue template

Added feature issue template

---

src/components/Auth/Register.tsx

I have modified the ui of the register page ,kindly check and inform me if you wanna any other chnages.
Closes #131
- [x ] My code adheres to the established style guidelines of the project.
- [x ] I have included comments in areas that may be difficult to understand.
- [ x] My changes have not introduced any new warnings.
- [x ] I have conducted a self-review of my code.

registration page updated

---

.github/workflows/prettier.yml

Closes #159 
Added linter workflow

Added linter

---

src/components/HomeHeader/HomeHeader.tsx
src/components/HomeHeader/styles.ts

https://github.com/Gaurav-Verma07/sampark/issues/40
- Hover effect was added on the navbar.
-  Animate the border from left to right when the user hovers.
https://github.com/Gaurav-Verma07/sampark/assets/83147410/321e4821-c8f3-455d-95e5-363da35e93c9

Hover effect added on navbar

---

src/components/Faq/Faq.tsx
src/components/Faq/Faqstyles.css

I have updated the CSS of the FAQ section as per your requirement , Kindly merge and if you wanna any other changes than please inform me .
Closes #172
- [x ] My code adheres to the established style guidelines of the project.
- [ x] I have included comments in areas that may be difficult to understand.
- [ x] My changes have not introduced any new warnings.
- [ x] I have conducted a self-review of my code.

FAQ CSS updated

---

src/components/Auth/Login.tsx

Closes #157 
- **Add Forgot Password Option in` Login.tsx File`.**
- **`Firebase Authentication Issues are  Major Problem in sampark Codebase.`**
- So, In this updated code, the "Forgot Password" link has been added the **` Logic.tsx `** However, the logic for handling the click event of the **`Forgot Password`** link is left empty. **`You should add your own implementation to handle the logic for the forgot password functionality, Such as showing a modal or navigating to a separate password reset page.`**
- **`Because of, Privacy and Security is Important.`**
- [x ] My code adheres to the established style guidelines of the project.
- [x ] I have included comments in areas that may be difficult to understand.
- [  ] My changes have not introduced any new warnings.
- [x ] I have conducted …

Add Forgot Password Option in Login.tsx File

---

src/App.tsx
src/Pages/Error/index.css
src/Pages/Error/index.tsx

Closes #183 
As described in the issue adde a route to error page and created a customised 404 error page

Created a 404 Error page

---

src/components/Auth/Register.tsx

Adding responsiveness on Register page

---

src/components/ContactUs/ContactUs.tsx

Closes #173
firebase realtime database is added to store user data from contact form . 
- [ x] My code adheres to the established style guidelines of the project.
- [x ] I have included comments in areas that may be difficult to understand.
- [x ] My changes have not introduced any new warnings.
- [x ] I have conducted a self-review of my code.

add firebase realtime database to store details from contact form [GSSOC'23] 

---

.github/workflows/close_old_issues.yaml

#162 bot added

---

src/components/ContactUs/ContactUs.tsx
src/utils/validation.ts

Closes #225 Contact form store invalid data.
Added inline Validation in the contact form.
https://github.com/Gaurav-Verma07/sampark/assets/86224794/1bd9f672-e2df-40ad-b38e-e00c3ea8d58d

contact-inline-validation

---

index.html
package-lock.json
src/App.css
src/App.tsx
src/Pages/Gallery/Gallery.tsx
src/Pages/Gallery/gallery.css
src/components/Auth/Register.tsx
src/components/HomeOurValues/Values.css
src/components/ImageGallery/ImageGallery.tsx
style.css

issue Solved: #223 
https://github.com/Gaurav-Verma07/sampark/assets/94003231/fd805200-539c-415c-8d4f-e7daafb57201

Add preloading Screen

---

package-lock.json
src/App.tsx
src/Pages/Gallery/Gallery.tsx
src/Pages/Gallery/gallery.css
src/components/Auth/Register.tsx
src/components/HomeOurValues/Values.css
src/components/ImageGallery/ImageGallery.tsx

Issue Solved: #222 
Also responsive

Added Gallery page

---

src/components/Navbar/Navbar.tsx
src/components/Navbar/styles.ts

#184 navbar fixed

---

package-lock.json
src/components/Auth/Register.tsx

Confirm password field is added

---

src/components/Auth/Register.tsx
src/utils/firebase.ts

Closes #155 
The firebase keys were consoled and and were visible inside the browser console which would have lead to unwanted breaches.
I have removed the lines where the keys were consoled in this PR. 
Before:
After:

Removed the lines where firebase env variables where consoled/exposed

---

package-lock.json
package.json
src/components/Auth/Login.tsx

please review @Gaurav-Verma07 sir
issue: #8

Add logo of website in sign-in page

---

server/index.ts
server/package.json
server/src/blogs/blog.router.ts
server/src/events/event.router.ts
server/src/ngos/ngo.router.ts
server/src/orphnages/orphanage.router.ts
server/src/users/user.router.ts
server/validationSchema/blogValidationSchema.ts
server/validationSchema/eventValidationSchema.ts
server/validationSchema/ngoValidationSchema.ts
server/validationSchema/orphanageValidationSchema.ts
server/validationSchema/userValidationSchema.ts

feat: add server side validation

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation-issue.md
.github/ISSUE_TEMPLATE/feature_request.md

Closes #87 
Added 3 issue templates - bug report, feature request & documentation related.

Updated issue templates

---

server/package.json
server/src/blogs/blog.router.ts
server/src/events/event.router.ts
server/src/middleware/auth.middleware.ts
server/src/ngos/ngo.router.ts
server/src/orphnages/orphanage.router.ts
server/src/users/user.router.ts

feat: auth middleware

---

package-lock.json
src/App.tsx
src/Pages/Error/index.css

Closes #274 and #261 
The 404 Not Found Page is now Mobile Responsive and Text is also visible
**Before**
**After**

404 Error Page Fixed

---

package-lock.json
src/App.tsx
src/components/Auth/Login.tsx
src/components/Auth/Register.tsx

Add back button in sign in and sign up page

---

src/components/Faq/Faq.tsx

feat:new  faq added

---

server/src/blogs/blog.router.ts
server/src/blogs/blog.service.ts
server/src/events/event.router.ts
server/src/events/event.service.ts
server/src/ngos/ngo.router.ts
server/src/ngos/ngo.service.ts
server/src/orphnages/orphanage.router.ts
server/src/orphnages/orphanage.service.ts

feat: routing for getstatic paths

---

app/globals.css
app/ngos/ngo.css
app/ngos/page.tsx
src/components/Ngos/NgosCard.tsx
src/components/Ngos/ngoContent.tsx

feat: add ngo page

---

app/globals.css
app/orphanages/orphanage.css
app/orphanages/page.tsx
src/components/Orphanages/OrphanagesCard.tsx
src/components/Orphanages/orphanageContent.ts

feat: add orphanage page

---

app/events/[slug]/page.tsx
server/schema/events/EventsSchema.ts
server/src/events/event.router.ts
server/validationSchema/eventValidationSchema.ts

Closes #334
Create and design a page for a single event. Populate the data from the backend routing using the next ^13.2 features

feat: add single event page

---

app/blogs/[slug]/page.tsx
server/schema/blogs/BlogsSchema.ts
server/src/blogs/blog.router.ts

Closes #335
Create and design a page for a single blog. Populate the data from the backend routing using the next ^13.2 features.

feat: add single blog page

---

app/orphanages/[slug]/page.tsx
server/src/orphnages/orphanage.router.ts

Closes#336
Create and design a page for a single orphanage. Populate the data from the backend routing using the next ^13.2 features

Feat: add single orphanage page

---

app/ngos/[slug]/page.tsx
server/schema/ngos/NgosSchema.ts
server/src/ngos/ngo.router.ts

Closes #337
Create and design single ngo page. Populate the data from the backend routing using the next ^13.2 features.

feat: add single ngo page

---

server/schema/impacts/ImpactsSchema.ts
server/validationSchema/impactValidationSchema.ts

Closes #333
create database schema for backend and also add backend validation schema for impact

feat: create database schema and backend validation for impact

---

server/src/impact/impact.interface.ts
server/src/impact/impact.router.ts
server/src/impact/impact.service.ts

Closes #332
Create routing and services for impact with all the type definition.

Feat: create routing and services for impact

---

server/schema/user/UserSchema.ts
server/validationSchema/userValidationSchema.ts

Closes #347
Updated the user validation and database

feat: user validation and database update

---

package.json
server/package-lock.json
server/package.json
src/components/Auth/Login.tsx
src/components/Auth/Register.tsx

Closes #348
add login and signup feature

feat: login signup feature

---

server/index.ts
server/src/users/user.interface.ts
server/src/users/user.router.ts
server/src/users/user.service.ts

Closes #348
Added login and sign up functionality in the backend

feat: user backend for login and signup

---

app/impact/[slug]/page.tsx
server/index.ts
server/schema/impacts/ImpactSchema.ts
server/src/impact/impact.router.ts
server/src/impact/impact.service.ts

Closes #350
Add page to show single impact data and also updated the impact schema in mongodb

Feat: add single impact page and updated impact schema

---

src/components/HomeOurValues/OurValues1.tsx
src/components/HomeOurValues/Values.css

Closes #346 
- Revamped the values section of homepage with best practices
|||
|:---:|:---:|
|**BEFORE**|![before](https://github.com/Gaurav-Verma07/sampark/assets/92252895/b9e66624-4ed5-4a6d-a761-236c629f17a0)|
|**AFTER**|![after](https://github.com/Gaurav-Verma07/sampark/assets/92252895/62fdc525-3e04-499e-8ebc-dfaa41ffd531)|

feat: revamp the values section of homepage 🪄✨ 

---

app/admin/page.tsx
app/api/admin/ngos/getall/route.ts
app/ngos/page.tsx
src/components/Admin/Ngos/AllNgos.tsx
src/components/Admin/Ngos/NgoAdminCard.tsx

Closes #361
create an admin panel to show ngo data for admins. Also, connected all Ngo page with the backend to fetch data and have shown them.

feat: admin panel for NGO and data fetch for all NGO page

---

app/admin/page.tsx
app/api/admin/blogs/getall/route.ts
app/blogs/page.tsx
src/components/Admin/Blog/AllBlogs.tsx
src/components/Admin/Blog/BlogAdminCard.tsx
src/components/Blogs/BlogCard.tsx

Closes #363
create an admin panel where all blogs will be shown, which is particularly for the admins. Also, connect all blogs page with the backend and fetch data from the database where all users can see orphanage page data.

feat: create admin panel for blog page and data fetching for all blog page

---

.github/workflows/issue-auto-assign.yml

Closes #299 
The Auto Issue Assignment feature is designed to automate the assignment of issues in a GitHub repository based on specific criteria. By leveraging GitHub Actions, this feature enables the automatic assignment of issues to users who meet predefined conditions, streamlining the issue management process and ensuring prompt attention to problems or tasks.

Auto assign feature added

---

app/admin/orphanage/add/page.tsx
app/admin/page.tsx
server/schema/orphanage/OrphanagesSchema.ts

Closes #365
I have updated the orphanage schema and create the orphanage form to add data

feat: orphanage form create and update orphanage schema

---

app/admin/ngo/add/page.tsx
server/schema/ngos/NgosSchema.ts

Closes #366
Add NGO form and update the ngo schema

feat: add ngo form and update ngo schema

---

app/admin/event/add/page.tsx
server/schema/events/EventsSchema.ts

Closes #364
Add event register form to add event data and update event register schema

feat: event registration form add and update event schema

---

app/admin/blog/add/page.tsx
server/schema/blogs/BlogsSchema.ts

Closes #367
Add form to add blogs and update blogschema

feat: add  form add blog and update blog schema

---

src/Pages/Seeker/index.tsx
src/components/Auth/Login.tsx
src/components/Auth/Register.tsx
src/components/ContactUs/ContactUs.tsx
src/components/ProviderCollegeTeam/ProviderCollegeTeam.tsx
src/components/ProviderMain/ProviderMain.tsx
src/utils/ApiRequests/firebaseAuth.ts
src/utils/ApiRequests/userProfile.ts

Closes #378 
- This PR addresses the issue of logging sensitive information in the browser's development console, which poses significant security risks and potential data breaches. 
- The logged data includes API keys, project identifiers, and other confidential information. 
- By removing the logs, we ensure better data protection and reduce the risk of unauthorized access and data leaks.

chore: remove important data leaking console logs from codebase 🙅🏻🔥 

---

src/components/MainHeader/styles.ts

Closes #380 
|C L O S E D &nbsp; S T A T E|O P E N E D &nbsp; S T A T E|
|:---:|:---:|
|![Screenshot 2023-08-06 at 15-03-53 Sampark](https://github.com/Gaurav-Verma07/sampark/assets/92252895/40730ca0-e398-49a6-a405-0b12f271a132) |![Screenshot 2023-08-06 at 15-03-24 Sampark](https://github.com/Gaurav-Verma07/sampark/assets/92252895/e3dac3f6-bd03-4059-bbe1-5b9978667491) |

fix: make side bar fully responsive for mobile devices 🪄✨ 

---

app/admin/orphanage/add/page.tsx
app/api/admin/orphanage/add/route.ts
server/src/orphnages/orphanage.interface.ts
server/src/orphnages/orphanage.router.ts
server/validationSchema/orphanageValidationSchema.ts

Closes #389
Add create functionality for orphanage data and validate orphanage shema

feat: add orphanage create and update orphanage validation

---

app/admin/event/add/page.tsx
app/api/admin/events/add/route.ts
server/schema/events/EventsSchema.ts
server/src/events/event.interface.ts
server/src/events/event.router.ts
server/validationSchema/eventValidationSchema.ts

Closes #390 
Add create functionality for event data and validate event schema

feat: add event data and update event validation

---

app/admin/event/edit/page.tsx
app/api/admin/events/edit/route.ts
app/api/admin/events/id/route.ts
server/src/events/event.router.ts

Closes #392
Add Edit functionality for event data

feat: add edit functionality in event

---

app/admin/page.tsx
app/api/admin/events/delete/route.ts
server/src/events/event.router.ts
src/components/Admin/Events/AllEvents.tsx
src/components/Admin/Events/EventsAdminCard.tsx

Closes #394
Add deletion feature for events

feat: add deleteion feature for events

---

app/admin/page.tsx
app/api/admin/orphanage/delete/route.ts
server/src/orphnages/orphanage.service.ts
src/components/Admin/Orphanages/AllOrphanages.tsx
src/components/Admin/Orphanages/OrphangeAdminCard.tsx

Closes #393
Add deletion functionality for orphanage

feat: add deletetion feature for orphanage

---

app/admin/ngo/add/page.tsx
app/api/admin/ngos/add/route.ts
server/src/ngos/ngo.interface.ts
server/src/ngos/ngo.router.ts
server/validationSchema/ngoValidationSchema.ts

Closes #409
Add ngo creation feature and update ngo validation

feat: add ngo create feature and update ngo validation

---

app/admin/ngo/edit/page.tsx
app/api/admin/ngos/edit/route.ts
app/api/admin/ngos/id/route.ts
server/src/ngos/ngo.router.ts

Closes #410
Added the feature to edit an existing ngo data

feat: add edit a particular ngo feature

---

app/api/admin/ngos/delete/route.ts
server/src/ngos/ngo.service.ts
src/components/Admin/Ngos/AllNgos.tsx
src/components/Admin/Ngos/NgoAdminCard.tsx

Closes #410
Added delete a particular NGO data

feat: delete a particular ngo feature

---

app/admin/blog/add/page.tsx
app/api/admin/blogs/add/route.ts
server/schema/blogs/BlogsSchema.ts
server/src/blogs/blog.interface.ts
server/src/blogs/blog.router.ts
server/validationSchema/blogValidationSchema.ts

Closes #412
Added blog create feature and update blog validation

feat: create blog feature and update blog validation

---

app/api/admin/blogs/delete/route.ts
server/src/blogs/blog.service.ts
src/components/Admin/Blog/AllBlogs.tsx
src/components/Admin/Blog/BlogAdminCard.tsx

Closes #413
Added feature to delete a particular blog

feat: add delete blog feature

---

app/admin/blog/edit/page.tsx
app/api/admin/blogs/edit/route.ts
app/api/admin/blogs/id/route.ts
server/src/blogs/blog.interface.ts
server/src/blogs/blog.router.ts

Closes #413
Add feature to edit an existing blog

feat: add edit feature for blogs
